{
  "login": "hackreactor",
  "id": 2824164,
  "node_id": "MDEyOk9yZ2FuaXphdGlvbjI4MjQxNjQ=",
  "url": "https://api.github.com/orgs/hackreactor",
  "repos_url": "https://api.github.com/orgs/hackreactor/repos",
  "hooks_url": "https://api.github.com/orgs/hackreactor/hooks",
  "issues_url": "https://api.github.com/orgs/hackreactor/issues",
  "members_url": "https://api.github.com/orgs/hackreactor/members{/member}",
  "public_members_url": "https://api.github.com/orgs/hackreactor/public_members{/member}",
  "description": "",
  "name": "Hack Reactor",
  "company": null,
  "location": "San Francisco, CA",
  "email": "contact@hackreactor.com",
  "public_repos": 33,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "html_url": "https://github.com/hackreactor",
  "created_at": "2012-11-17T23:58:54Z",
  "updated_at": "2021-03-11T14:53:01Z",
  "type": "Organization",
  "total_private_repos": 15928,
  "owned_private_repos": 15913,
  "private_gists": 0,
  "disk_usage": 14183503,
  "collaborators": 1023,
}