{
    "login": "magee",
    "id": 15180,
    "node_id": "MDQ6VXNlcjE1MTgw",
    "url": "https://api.github.com/users/magee",
    "html_url": "https://github.com/magee",
    "gists_url": "https://api.github.com/users/magee/gists{/gist_id}",
    "organizations_url": "https://api.github.com/users/magee/orgs",
    "repos_url": "https://api.github.com/users/magee/repos",
    "type": "User",
    "site_admin": false,
    "name": "Magee Mooney",
    "company": "@hackreactor @gSchool ",
    "location": "SF Bay Area, California",
    "email": null,
    "created_at": "2008-06-26T19:31:07Z",
    "updated_at": "2022-02-03T23:27:25Z",
    "private_gists": 25,
    "total_private_repos": 208,
    "owned_private_repos": 23,
    "disk_usage": 376729,
}